-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.psitions
(
    position_id integer NOT NULL,
    position_name character varying(100) NOT NULL,
    PRIMARY KEY (position_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.personels
(
    personal_id integer NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    PRIMARY KEY (personal_id)
);

CREATE TABLE public.candicates
(
    candicate_id integer NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    nationality_id character varying(100) NOT NULL,
    birth_date date NOT NULL,
    PRIMARY KEY (candicate_id)
);

CREATE TABLE public.employers
(
    employer_id integer NOT NULL,
    company_name character varying(100) NOT NULL,
    website character varying(100) NOT NULL,
    phone_number character varying(11) NOT NULL,
    company_verify boolean NOT NULL,
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.mernis_verification
(
    mernis_id integer NOT NULL,
    "mernis verify" boolean NOT NULL,
    PRIMARY KEY (mernis_id)
);

CREATE TABLE public.email_verification
(
    email_verify_id integer NOT NULL,
    email_verify boolean NOT NULL,
    PRIMARY KEY (email_verify_id)
);

CREATE TABLE public.company_verification
(
    company_verify_id integer NOT NULL,
    company_verify boolean NOT NULL,
    PRIMARY KEY (company_verify_id)
);

ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.employers (employer_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.candicates (candicate_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.personels (personal_id)
    NOT VALID;


ALTER TABLE public.mernis_verification
    ADD FOREIGN KEY (mernis_id)
    REFERENCES public.candicates (candicate_id)
    NOT VALID;


ALTER TABLE public.email_verification
    ADD FOREIGN KEY (email_verify_id)
    REFERENCES public.employers (employer_id)
    NOT VALID;


ALTER TABLE public.company_verification
    ADD FOREIGN KEY (company_verify_id)
    REFERENCES public.employers (employer_id)
    NOT VALID;

END;